/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fjff;

import javax.swing.JOptionPane;

/**
 *
 * @author FJFF
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelmaintitle = new javax.swing.JLabel();
        labelpassword = new javax.swing.JLabel();
        labeluser = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtpassword = new javax.swing.JPasswordField();
        btnexit = new javax.swing.JButton();
        btnenter = new javax.swing.JButton();
        labelmyname = new javax.swing.JLabel();
        labeliconuser = new javax.swing.JLabel();
        labelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelmaintitle.setBackground(new java.awt.Color(0, 0, 0));
        labelmaintitle.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        labelmaintitle.setForeground(new java.awt.Color(255, 255, 255));
        labelmaintitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelmaintitle.setText("SISTEMA DE INVENTARIO");
        getContentPane().add(labelmaintitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 60));

        labelpassword.setFont(new java.awt.Font("Fast Hand", 0, 24)); // NOI18N
        labelpassword.setForeground(new java.awt.Color(255, 255, 255));
        labelpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelpassword.setText("CLAVE");
        getContentPane().add(labelpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 610, -1));

        labeluser.setFont(new java.awt.Font("Fast Hand", 0, 24)); // NOI18N
        labeluser.setForeground(new java.awt.Color(255, 255, 255));
        labeluser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeluser.setText("USUARIO");
        getContentPane().add(labeluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 610, -1));

        txtuser.setBackground(new java.awt.Color(51, 51, 51));
        txtuser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        txtuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtuser.setOpaque(true);
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 160, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 420, 20));

        txtpassword.setBackground(new java.awt.Color(51, 51, 51));
        txtpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword.setOpaque(true);
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 160, 40));

        btnexit.setBackground(new java.awt.Color(102, 0, 0));
        btnexit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 255, 255));
        btnexit.setText("SALIR");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        btnenter.setBackground(new java.awt.Color(51, 51, 51));
        btnenter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnenter.setForeground(new java.awt.Color(255, 255, 255));
        btnenter.setText("ENTRAR");
        btnenter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenterActionPerformed(evt);
            }
        });
        getContentPane().add(btnenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 90, 40));

        labelmyname.setForeground(new java.awt.Color(255, 255, 255));
        labelmyname.setText("by : Franger Fernandez");
        getContentPane().add(labelmyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        labeliconuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeliconuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/97b2c49b945fa26e0f807827d35a8c38 (1) (2).png"))); // NOI18N
        getContentPane().add(labeliconuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 610, 70));

        labelfondo.setBackground(new java.awt.Color(204, 204, 204));
        labelfondo.setForeground(new java.awt.Color(0, 0, 0));
        labelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/istockphoto-1807779771-612x612.jpg"))); // NOI18N
        labelfondo.setText("LOGIN");
        getContentPane().add(labelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por usar mi programa, hasta luego!");
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtuserActionPerformed

    private void btnenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenterActionPerformed
        // TODO add your handling code here:
        String user = txtuser.getText();
        String password = txtpassword.getText();

        if(user.equals("franger") && (password.equals("29931566")))
        {
            JOptionPane.showMessageDialog(null, "Datos correctos!");
            menu frm = new menu();
            frm.setVisible(true);
            this.dispose();

        }

        else
        {
            JOptionPane.showMessageDialog(null, "Usuario o clave incorrectos");
            txtuser.setText("");
            txtpassword.setText("");
        }
          
    }//GEN-LAST:event_btnenterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenter;
    private javax.swing.JButton btnexit;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelfondo;
    private javax.swing.JLabel labeliconuser;
    private javax.swing.JLabel labelmaintitle;
    private javax.swing.JLabel labelmyname;
    private javax.swing.JLabel labelpassword;
    private javax.swing.JLabel labeluser;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}