/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fjff;

import javax.swing.JOptionPane;

/**
 *
 * @author FJFF
 */
public class registro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(registro.class.getName());

    /**
     * Creates new form registro
     */
    public registro() {
       initComponents();
       setLocationRelativeTo(null);
       tablaregistro.setModel(DatosCompartidos.getModelo());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaregistro = new javax.swing.JTable();
        btnback = new javax.swing.JButton();
        brnexit = new javax.swing.JButton();
        labelid = new javax.swing.JLabel();
        labelqty = new javax.swing.JLabel();
        labelname = new javax.swing.JLabel();
        labelprice = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        labelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaregistro.setBackground(new java.awt.Color(255, 255, 255));
        tablaregistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablaregistro.setForeground(new java.awt.Color(0, 0, 0));
        tablaregistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "CANTIDAD", "PRECIO"
            }
        ));
        tablaregistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaregistro.setSelectionBackground(new java.awt.Color(0, 0, 255));
        tablaregistro.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablaregistro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 600, 210));

        btnback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnback.setText("ATRAS");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        brnexit.setBackground(new java.awt.Color(102, 0, 0));
        brnexit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        brnexit.setForeground(new java.awt.Color(255, 255, 255));
        brnexit.setText("SALIR");
        brnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnexitActionPerformed(evt);
            }
        });
        getContentPane().add(brnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        labelid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelid.setForeground(new java.awt.Color(255, 255, 255));
        labelid.setText("ID :");
        getContentPane().add(labelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        labelqty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelqty.setForeground(new java.awt.Color(255, 255, 255));
        labelqty.setText("CANTIDAD :");
        getContentPane().add(labelqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        labelname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelname.setForeground(new java.awt.Color(255, 255, 255));
        labelname.setText("NOMBRE :");
        getContentPane().add(labelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        labelprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelprice.setForeground(new java.awt.Color(255, 255, 255));
        labelprice.setText("PRECIO :");
        getContentPane().add(labelprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtid.setBackground(new java.awt.Color(255, 255, 255));
        txtid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtid.setForeground(new java.awt.Color(0, 0, 0));
        txtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 150, 40));

        txtname.setBackground(new java.awt.Color(255, 255, 255));
        txtname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 0));
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 160, 40));

        txtprice.setBackground(new java.awt.Color(255, 255, 255));
        txtprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtprice.setForeground(new java.awt.Color(0, 0, 0));
        txtprice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 150, 40));

        txtqty.setBackground(new java.awt.Color(255, 255, 255));
        txtqty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtqty.setForeground(new java.awt.Color(0, 0, 0));
        txtqty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 160, 40));

        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnadd.setText("AGREGAR");
        btnadd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnclear.setText("LIMPIAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        labelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/12.jpg"))); // NOI18N
        labelfondo.setText("jLabel1");
        getContentPane().add(labelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnexitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por usar mi programa, hasta luego!");
        System.exit(0);
    }//GEN-LAST:event_brnexitActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        menu frm = new menu();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtid.setText("");
        txtname.setText("");
        txtqty.setText("");
        txtprice.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String id = txtid.getText();
        String nombre = txtname.getText();
        String cantidad = txtqty.getText();
        String precio = "$ " + txtprice.getText();
        DatosCompartidos.getModelo().addRow(new Object[]{id, nombre, cantidad, precio});
        
        txtid.setText("");
        txtname.setText("");
        txtqty.setText("");
        txtprice.setText("");
    }//GEN-LAST:event_btnaddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new registro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnexit;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelfondo;
    private javax.swing.JLabel labelid;
    private javax.swing.JLabel labelname;
    private javax.swing.JLabel labelprice;
    private javax.swing.JLabel labelqty;
    private javax.swing.JTable tablaregistro;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables
}
